spring:
    main.banner-mode: off
    mvc.log-resolved-exception: false
    devtools.restart.log-condition-evaluation-delta: false
    jpa:
        open-in-view: false
        hibernate.ddl-auto: none
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    liquibase:
        enabled: true
    mail:
        host: localhost
        default-encoding: UTF-8
        test-connection: false
    web:
        locale: en_US
    security.oauth2.client.provider.facebook:
        user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture

jmpsl:
    security:
        ota:
            length: 10

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} %5level [%15thread] %-50logger{36} : %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} %5level [%15thread] %-50logger{36} : %msg%n"
    file:
        max-history: 40
        max-size: 10MB

config:
    mail-helpdesk-agent: helpdesk
    cors-max-age-seconds: 3600
    redirects:
        change-password-uri: /auth/change-password
        activate-account-uri: /activate-account
        unsubscribe-newsletter-uri: /unsubscribe-newsletter

authorization:
    one-time-access-token:
        token-expired-minutes: 10
    bearer-token:
        token-expired-minutes: 5
    refresh-token:
        token-expired-months: 3
    oauth2-custom:
        password-replacer: ${env.DEV_PROD_OAUTH2_PASSWORD_REPLACER}
