spring:
  main.banner-mode: off
  mvc.log-resolved-exception: false
  devtools.restart.log-condition-evaluation-delta: false
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    enabled: true
  mail:
    host: localhost
    default-encoding: UTF-8
    test-connection: false
  web:
    locale: en_US
  security.oauth2.client.provider.facebook:
    user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %5level [%15thread] %-50logger{36} : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %5level [%15thread] %-50logger{36} : %msg%n"
  file:
    max-history: 40
    max-size: 10MB

config:
  newsletter-unsubscribe-path: /unsubscribe-newsletter/
  mail-helpdesk-agent: helpdesk
  cors-max-age-seconds: 3600

authorization:
  one-time-access-token:
    token-expired-minutes: 10
    token-length: 10
  bearer-token:
    token-expired-minutes: 5
  oauth2-custom:
    session-remember-cookie-name: oauth2_auth_request
    redirect-uri-cookie-name: redirect_uri
    cookie-expired-minutes: 3
