spring:
    main.banner-mode: off
    mvc.log-resolved-exception: false
    devtools.restart.log-condition-evaluation-delta: false
    jpa:
        open-in-view: false
        hibernate.ddl-auto: none
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    liquibase:
        enabled: true
    mail:
        host: localhost
        default-encoding: UTF-8
        test-connection: false
    web:
        locale: en_US
    security.oauth2.client.provider.facebook:
        user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture

jmpsl:
    security:
        oauth2-active: true
        ota:
            length: 10
    mail:
        freemarker-templates-dir: classpath:/templates
    oauth2:
        cookie-expired-minutes: 3
        available-suppliers: google,facebook
    file:
        ssh:
            socket-host: ${env.DEV_PROD_SSH_SOCKET_HOST}
            socket-login: ${env.DEV_PROD_SSH_SOCKET_LOGIN}
            known-hosts-file-name: known_hosts.dat
            user-private-key-file-name: id_rsa
        sftp:
            server-url: ${env.DEV_PROD_SFTP_SERVER_URL}
        basic-external-server-path: ${env.DEV_PROD_ROOT_SERVER_PATH}
        app-external-server-path: chess-app-static-resources
        hash-code:
            separator: "-"
            count-of-sequences: 4
            sequence-length: 5
    gfx:
        user-gfx:
            preferred-font-link: static/font/noto-serif-v21-latin-regular.ttf
            preferred-font-name: Noto Serif
            static-images-content-path: images

logging:
    file:
        max-history: 40
        max-size: 10MB

config:
    mail-helpdesk-agent: helpdesk
    cors-max-age-seconds: 3600
    redirects:
        change-password-uri: /auth/change-password
        activate-account-uri: /activate-account
        unsubscribe-newsletter-uri: /unsubscribe-newsletter
    profile-image:
        size-px: 200
        font-size-px: 80
    banner-image:
        size-width-px: 2500
        size-height-px: 320

authorization:
    one-time-access-token:
        token-expired-minutes: 10
    bearer-token:
        token-expired-minutes: 5
    refresh-token:
        token-expired-months: 3
    oauth2-custom:
        password-replacer: ${env.DEV_PROD_OAUTH2_PASSWORD_REPLACER}
