config:
    base-url: http://localhost:9595
    frontend-cors-url: http://localhost:4200
    frontend-name: localhost
    authorization:
        password-encoder-strength: 4

server:
    port: 9595

jmpsl:
    auth:
        jwt:
            secret: daw94289vndq98198nkejfnkaendwef93892fnskjdenfkjeiwefibiu32983fnskjdfn
            issuer: localhost

spring:
    devtools.livereload.port: 35731
    h2.console.enabled: true
    liquibase:
        drop-first: false
        change-log: classpath:db/changelog/db.changelog-dev.xml
    datasource:
        url: jdbc:h2:file:./h2-db
        username: sa
        driver-class-name: org.h2.Driver
    mail:
        protocol: smtp
        port: 465
        host: ${env.PROD_SMTP_MAIL_AGENT}
        username: ${env.PROD_SMTP_MAIL_USERNAME}
        password: ${env.PROD_SMTP_MAIL_PASSWORD}
        properties:
            smtp.starttls.required: true
            mail.smtp:
                ssl.enable: true
                auth: true
                starttls.enable: true
    security.oauth2.client.registration:
        google:
            clientId: ${env.DEV_OAUTH2_GOOGLE_CLIENT_ID}
            clientSecret: ${env.DEV_OAUTH2_GOOGLE_CLIENT_SECRET}
        facebook:
            clientId: ${env.DEV_OAUTH2_FACEBOOK_CLIENT_ID}
            clientSecret: ${env.DEV_OAUTH2_FACEBOOK_CLIENT_SECRET}

oauth2-custom:
    token-secret: ${env.DEV_OAUTH2_TOKEN_SECRET}
    token-expiration-hours: 24
    redirect-uris: http://localhost:4200/oauth2/redirect,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect

logging:
    level:
        org.hibernate.sql: DEBUG
