server:
  port: 7575

config:
  frontend-cors-url: http://127.0.0.1:4200
  authorization:
    jwt-key: daw94289vndq98198nkejfnkaendwef93892fnskjdenfkjeiwefibiu32983fnskjdfn

spring:
  devtools.livereload.port: 35731
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:file:./h2-db
    username: sa
    driver-class-name: org.h2.Driver