config:
    base-url: http://localhost:9595
    frontend-cors-url: http://localhost:4200
    frontend-name: localhost

server:
    port: 9595

jmpsl:
    security:
        password-encoder-strength: 4
        jwt:
            secret: daw94289vndq98198nkejfnkaendwef93892fnskjdenfkjeiwefibiu32983fnskjdfn
            issuer: localhost
        cors:
            client: http://localhost:4200
    oauth2:
        redirect-uris: http://localhost:4200/oauth2/redirect,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect

spring:
    devtools.livereload.port: 35731
    h2.console.enabled: true
    liquibase:
        drop-first: false
        change-log: classpath:db/changelog/db.changelog-dev.xml
    datasource:
        url: jdbc:h2:file:./h2-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        driver-class-name: org.h2.Driver
    mail:
        protocol: smtp
        port: 25
        host: localhost
        username: noreply-dev@localhost
        password: admin
        properties:
            smtp.starttls.required: false
            mail.smtp:
                ssl.enable: false
                auth: true
                starttls.enable: false
    security.oauth2.client.registration:
        google:
            clientId: ${env.DEV_OAUTH2_GOOGLE_CLIENT_ID}
            clientSecret: ${env.DEV_OAUTH2_GOOGLE_CLIENT_SECRET}
        facebook:
            clientId: ${env.DEV_OAUTH2_FACEBOOK_CLIENT_ID}
            clientSecret: ${env.DEV_OAUTH2_FACEBOOK_CLIENT_SECRET}
    jpa:
        show-sql: false

oauth2-custom:
    token-secret: ${env.DEV_OAUTH2_TOKEN_SECRET}
    token-expiration-hours: 24
