spring:
  main.banner-mode: off
  mvc.log-resolved-exception: false
  devtools.restart.log-condition-evaluation-delta: false
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: localhost
    default-encoding: UTF-8
    test-connection: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %5level [%15thread] %-50logger{36} : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %5level [%15thread] %-50logger{36} : %msg%n"

config:
  newsletter-unsubscribe-path: /unsubscribe-newsletter/
  mail-helpdesk-agent: helpdesk

authorization:
  one-time-access-token:
    token-expired-minutes: 10
    token-length: 10
  bearer-token:
    token-expired-minutes: 5
