config:
  frontend-cors-url: http://127.0.0.1:4200
  frontend-name: localhost
  authorization:
    jwt-key: daw94289vndq98198nkejfnkaendwef93892fnskjdenfkjeiwefibiu32983fnskjdfn
    jwt-issuer: localhost
server:
  port: 7575

spring:
  devtools.livereload.port: 35731
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:file:./h2-db
    username: sa
    driver-class-name: org.h2.Driver
  mail:
    protocol: smtp
    port: 25
    host: localhost
    username: noreply-dev@localhost
    password: admin
    properties:
      smtp.starttls.required: false
      mail.smtp:
        ssl.enable: false
        auth: true
        starttls.enable: false
